version: '3.7'

services:
  neo4j:
    image: neo4j:latest
    container_name: "neo4j"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/test
      - apoc.import.file.enabled=true
      # - NEO4J_dbms_memory_pagecache_size=4G
      # - NEO4j_dbms_memory_heap_initial__size=4G
      # - NEO4J_dbms_memory_heap_max__size=8G
    networks:
      - neo_net

  jupyterlab:
    image: jupyter/pyspark-notebook:spark-3.1.2
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan
      - ./jars:/home/jovyan/jars
      - ./data:/home/jovyan/data
    environment:
      - JUPYTER_TOKEN=easy
    links:
      - neo4j
    networks:
      - neo_net
    command: start.sh jupyter lab --LabApp.token=''

networks:
  neo_net:    